apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.service.port }}
            protocol: TCP
          command: ["sh", "-c", "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: sql-url
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: sql-name 
            - name: DB_USER
              value: djawed
            - name: DB_PASSWORD
              value: djawed