apiVersion: v1
kind: Pod
metadata:
  name: db-pod
spec:
  containers:
  - name: db-container
    image: mysql:latest
    env:
    - name: MYSQL_DATABASE
      value: django-app-db

    - name: MYSQL_ROOT_PASSWORD
      value: root_pw

    - name: MYSQL_USER
      value: djawed

    - name: MYSQL_PASSWORD
      value: djawed

    ports:
    - containerPort: 3306

---
# service to expose this application

apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db-pod
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306


