apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: sql-configmap
              key: db-name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_root_password
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  type: ClusterIP  
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306

