apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: djawed22/repo:vtest
        ports:
        - containerPort: 8000
        env:
        - name: DB_NAME
          value: 'django-app-db'
        - name: DB_USER
          value: 'djawed'
        - name: DB_PASSWORD
          value: 'djawed'
        - name: DB_HOST
          value: 'mysql-service'
        - name: DB_PORT
          value: '3306'
---
apiVersion: v1
kind: Service
metadata:
  name: django-app-service
spec:
  selector:
    app: django-app
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: NodePort     
