apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: djawed22/repo:latest
        ports:
        - containerPort: 8000
        command: ["sh", "-c", "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: sql-config
              key: sql-url
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: sql-config
              key: sql-name 
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: sql-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: sql-password
---                               
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
