apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  name: sql-deployment
  labels:
    app: sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
      - name: sql-db
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: sql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: sql-config
              key: sql-name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: sql-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: sql-password  
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: sql-service
spec:
  selector:
    app: sql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306 