apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deployment
  labels:
    app: sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
      - name: sql-db
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        # - name: MYSQL_ROOT_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: sql-secret
        #       key: sql-database-user-password
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"

        - name: MYSQL_DATABASE
          value: django-app-db
          # valueFrom:
          #   configMapKeyRef:
          #     name: sql-config
          #     key: sql-name
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: sql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
