version: "3.3"
services:
  app:
    #build: .
    volumes:
     - .:/django
    ports:
     - 8000:8000
    image: djawed22/repo:latest
    restart: always
    container_name: django_container
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"

    depends_on:
    - db
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'django-app-db'
      MYSQL_USER: 'djawed'
      MYSQL_PASSWORD: 'djawed'
      MYSQL_ROOT_PASSWORD: 'djawed'
    volumes:
     - ./mysql:/var/lib/mysql
    ports:
     - 3306:3306