FROM python:3.8

ENV PYTHONUNBUFFERED=1
ENV DB_NAME='django-app-db'
ENV DB_USER='djawed'
ENV DB_PASSWORD='djawed'
ENV DB_HOST='db'
ENV DB_PORT=3306

WORKDIR /django

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .


