FROM python:3.8

ENV PYTHONUNBUFFERED=1
ENV DB_NAME=
ENV DB_USER=root
ENV DB_PASSWORD=
ENV DB_HOST=
ENV DB_PORT=

WORKDIR /django

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . . 

# Update the settings.py file to use the environment variables for the database connection details
RUN sed -i 's/localhost/$DB_HOST/g' /django/mysite/settings.py
RUN sed -i 's/3306/$DB_PORT/g' /django/mysite/settings.py
RUN sed -i "s/'NAME': 'django-app-db',/'NAME': os.environ.get('DB_NAME', 'django-app-db'),/" /django/mysite/settings.py
RUN sed -i "s/'USER': 'root',/'USER': os.environ.get('DB_USER', 'root'),/" /django/mysite/settings.py
RUN sed -i "s/'PASSWORD': '',/'PASSWORD': os.environ.get('DB_PASSWORD', ''),/" /django/mysite/settings.py
