FROM python:3.8

ENV PYTHONUNBUFFERED=1
ENV DB_NAME ""
ENV DB_USER ""
ENV DB_PASSWORD ""
ENV DB_HOST ""
ENV DB_PORT 3306

WORKDIR /django

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .


